scrape_configs:
  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['192.168.112.139:8081']
        labels:
          application: 'My Spring Boot Application'